[project]
name = "studentuselogger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "chi1180", email = "c205297@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "kokoro>=0.9.4",
    "misaki[ja]>=0.9.4",
    "numpy>=2.4.6",
    "opencv-python>=5.0.0.93",
    "pillow>=12.3.0",
    "pytesseract>=0.3.13",
    "soundfile>=0.14.0",
]

[project.scripts]
studentuselogger = "studentuselogger:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
